# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

baseurl: /ChinaFlyingGooseStamps
auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 100 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

